// Texto do modelo oficial de contrato (CONTRATO_2026.pdf) — mantido fiel ao original.
export const EMPRESA = {
  titulo: 'CONTRATO PARA LOCAÇÃO',
  razao: 'ZIMBA FESTAS LOCAÇÃO DE BRINQUEDOS',
  fantasia: 'ZIMBA FESTAS',
  cnpj: '47.913.609/0001-15',
  site: 'WWW.ZIMBAFESTAS.COM.BR',
  email: 'CONTATO@ZIMBAFESTAS.COM.BR',
  chavePix: '47.913.609/0001-15 (CNPJ)',
};

export const CLAUSULAS: { titulo: string; texto: string }[] = [
  {
    titulo: 'REGRAS GERAIS',
    texto:
      'É DE RESPONSABILIDADE DO CONTRATANTE GARANTIR O CUIDADO E O USO CORRETO DOS BRINQUEDOS LOCADOS, BEM COMO TODO O CUIDADO E MONITORAMENTO DAS CRIANÇAS. É PROIBIDA A ENTRADA NOS BRINQUEDOS COM CALÇADOS, COMIDAS, BEBIDAS, OUTROS BRINQUEDOS OU OBJETOS QUE POSSAM DANIFICÁ-LOS (COMO TINTAS, BRINCOS, CORRENTES, ETC.). RECOMENDAMOS NÃO ENTRAR COM JOIAS E CELULARES, POIS NÃO NOS RESPONSABILIZAMOS POR ITENS PERDIDOS DURANTE O USO DO BRINQUEDO. EM CASO DE CHUVA MODERADA, OS MOTORES DEVEM ESTAR TOTALMENTE PROTEGIDOS (DEIXAMOS UM BANCO EM CIMA DOS MOTORES NA MONTAGEM COM UMA LONA EM CIMA, CABENDO AO CLIENTE APENAS MONITORAR SE A PROTEÇÃO CONTINUA DEVIDAMENTE POSICIONADA). EM CASO DE CHUVA FORTE, OS MOTORES DEVEM SER RETIRADOS PELO CONTRATANTE PARA EVITAR QUE O VENTO ARRASTE O BRINQUEDO JUNTO COM O MOTOR, OCASIONANDO A QUEIMA. É PROIBIDO O USO DO BRINQUEDO COM O MOTOR EXPOSTO À CHUVA OU À ÁGUA, POIS O MESMO NÃO POSSUI PROTEÇÃO CONTRA LÍQUIDOS. OS MOTORES NÃO PODEM SER TOTALMENTE COBERTOS DURANTE O FUNCIONAMENTO PARA NÃO QUEIMAREM POR FALTA DE RESFRIAMENTO, E A TOMADA DO MOTOR NÃO DEVE SER ALTERADA APÓS A INSTALAÇÃO PARA ENERGIA 220V, POIS QUEIMARÁ (ALGUNS DOS NOSSOS MOTORES SÃO 110V, SEMPRE FAZEMOS O TESTE NA TOMADA ANTES DA INSTALAÇÃO E COLOCAMOS TRANSFORMADOR, SE NECESSÁRIO).',
  },
  {
    titulo: '1',
    texto:
      'O VALOR RESTANTE ACORDADO DEVERÁ SER PAGO NO MOMENTO DA NOSSA CHEGADA, ANTES DA MONTAGEM DOS BRINQUEDOS, E NÃO AO FINAL DA FESTA. O PAGAMENTO PODE SER FEITO VIA DINHEIRO, PIX OU CARTÃO (COM ACRÉSCIMO DA TAXA DA MÁQUINA). CASO O PAGAMENTO NÃO SEJA REALIZADO, A PRESTAÇÃO DO SERVIÇO SERÁ CANCELADA. GARANTIMOS QUE TODOS OS NOSSOS BRINQUEDOS SE ENCONTRAM EM ÓTIMAS CONDIÇÕES DE USO; CASO CONTRÁRIO, ASSEGURAMOS A DEVOLUÇÃO INTEGRAL DO VALOR PAGO PELO CLIENTE E O CANCELAMENTO DO SERVIÇO.',
  },
  {
    titulo: '2',
    texto:
      'EM CASO DE AVARIA GRAVE, EXTRAVIO, DANO GRAVE OU FURTO DO MATERIAL LOCADO, A LOCADORA SE RESERVA O DIREITO DE EMITIR COBRANÇA BANCÁRIA AO CONTRATANTE NO VALOR CORRESPONDENTE AO REPARO OU À SUBSTITUIÇÃO DO BEM, A QUAL DEVERÁ SER PAGA NO MESMO DIA. DANOS DECORRENTES DO USO NORMAL DOS BRINQUEDOS NÃO SÃO COBRADOS, APENAS AQUELES RESULTANTES DE MAU USO PROPOSITAL ETC.',
  },
  {
    titulo: '3',
    texto:
      'FICA COMO RESPONSABILIDADE DO CLIENTE GARANTIR UM LOCAL CORRETO PARA A INSTALAÇÃO DO BRINQUEDO, COM ESPAÇO ADEQUADO PARA O MESMO (LONGE DE PAREDE, CALHAS, TETO E OUTROS OBJETOS). NÃO FAZEMOS MONTAGENS EM ESPAÇO DE AREIA E BARRO. É TAMBÉM RESPONSABILIDADE DO CONTRATANTE FORNECER PONTO DE ENERGIA ESTÁVEL PARA OS BRINQUEDOS INFLÁVEIS E TORNEIRA TIPO COMUM (BICO COM ROSCA DE 3/4 DE POLEGADA) COM ÁGUA PRÓXIMO AOS BRINQUEDOS DE ÁGUA (FUTEBOL DE SABÃO).',
  },
  {
    titulo: '4',
    texto:
      'NOSSOS BRINQUEDOS SERÃO INSTALADOS APENAS EM LOCAIS PLANOS, SEM GRANDES INCLINAÇÕES, DEGRAUS OU DECLIVES (COMO CALÇADAS), E DISTANTES DE ÁREAS QUE POSSAM APRESENTAR RISCO ÀS CRIANÇAS OU AO PRÓPRIO EQUIPAMENTO. NÃO REALIZAMOS A MONTAGEM EM LOCAIS DE DIFÍCIL ACESSO, TAIS COMO MORROS E LADEIRAS, QUE IMPEÇAM OU DIFICULTEM A PASSAGEM E O TRANSPORTE DO MATERIAL. LOCAIS COM ESCADAS DEPENDEM DE NOSSA CONFIRMAÇÃO PRÉVIA À RESERVA, VISTO QUE ALGUNS BRINQUEDOS MAIS PESADOS NÃO PODEM SER TRANSPORTADOS POR ESSA VIA. EM CASO DE AUSÊNCIA DE CONFIRMAÇÃO, NÃO NOS RESPONSABILIZAMOS PELA IMPOSSIBILIDADE DA PRESTAÇÃO DO SERVIÇO.',
  },
  {
    titulo: '5',
    texto:
      'MESMO APÓS A EMISSÃO DO CONTRATO, A RESERVA DO BRINQUEDO SÓ É EFETIVADA APÓS A CONFIRMAÇÃO DO RECEBIMENTO DO SINAL ACORDADO. ATÉ QUE ISSO OCORRA, O EQUIPAMENTO PERMANECE DISPONÍVEL PARA OUTROS CLIENTES, VISTO QUE A EMISSÃO PRÉVIA DO CONTRATO É APENAS PARA A CONFERÊNCIA DAS INFORMAÇÕES POR PARTE DO CONTRATANTE.',
  },
  {
    titulo: '6',
    texto:
      'NOSSOS BRINQUEDOS NÃO ACOMPANHAM MONITORES, COM EXCEÇÕES PONTUAIS EM EVENTOS GRANDES E FESTAS DE SEGUNDA A SEXTA-FEIRA, ONDE O SERVIÇO É PAGO À PARTE E EXPLICITAMENTE DESCRITO NO CAMPO DE DESCRIÇÃO DO ITEM. PORTANTO, A RESPONSABILIDADE PELO CUIDADO E ACOMPANHAMENTO DAS CRIANÇAS DURANTE TODO O PERÍODO DA LOCAÇÃO É INTEIRAMENTE DO CONTRATANTE.',
  },
  {
    titulo: '7',
    texto:
      'APÓS A CONFIRMAÇÃO DA RESERVA, ALTERAÇÕES DE DATA OU HORÁRIO SÓ PODERÃO SER REALIZADAS COM ANTECEDÊNCIA ADEQUADA E ESTÃO SUJEITAS A VARIAÇÕES DE VALORES CASO A NOVA DATA POSSUA PREÇO DIFERENTE. PRÓXIMO À DATA DA MONTAGEM, MUDANÇAS DE HORÁRIO SERÃO ANALISADAS APENAS SE NÃO IMPACTAREM A NOSSA OPERAÇÃO; CASO CONTRÁRIO, NENHUMA MODIFICAÇÃO SERÁ PERMITIDA, VISTO QUE NOSSA LOGÍSTICA É PLANEJADA PREVIAMENTE E A EQUIPE, OS VEÍCULOS E OS EQUIPAMENTOS SÃO RESERVADOS EXCLUSIVAMENTE PARA O SEU ATENDIMENTO. JÁ AS ALTERAÇÕES DE DATA SÓ SERÃO ACEITAS COM AMPLA ANTECEDÊNCIA OU EM CASOS COMPROVADOS DE FORÇA MAIOR, COMO MOTIVOS DE SAÚDE DO CONTRATANTE, CÔNJUGE OU FILHOS (COMPROVADOS POR ATESTADO MÉDICO), DESASTRES NATURAIS OU CRISES SANITÁRIAS GRAVES. PARA EVENTOS EM LOCAIS ABERTOS, A PROTEÇÃO CONTRA A CHUVA É DE TOTAL RESPONSABILIDADE DO CONTRATANTE, QUE DEVERÁ PROVIDENCIAR LONA, TOLDO OU UM ESPAÇO COBERTO ALTERNATIVO. CASO ISSO NÃO SEJA FEITO, AUTORIZAMOS O USO DOS BRINQUEDOS INFLÁVEIS SOB CHUVA MODERADA, DESDE QUE OS MOTORES PERMANEÇAM PROTEGIDOS CONFORME DEIXADOS NA MONTAGEM, CABENDO AO CLIENTE APENAS MONITORAR SE A PROTEÇÃO CONTINUA POSICIONADA. SE ESTIVER CHOVENDO MUITO NO MOMENTO DA MONTAGEM E O CLIENTE OPTAR POR NÃO PROSSEGUIR COM O SERVIÇO NAQUELE DIA, PERMITIREMOS UM ÚNICO REAGENDAMENTO GRATUITO, VÁLIDO EXCLUSIVAMENTE PARA DIAS DE SEMANA (DE SEGUNDA A SEXTA-FEIRA, EXCETO FERIADOS E DATAS COMEMORATIVAS) E SUJEITO À DISPONIBILIDADE DA NOSSA AGENDA. COMO OS FATORES CLIMÁTICOS FOGEM AO NOSSO CONTROLE, NÃO HAVERÁ REEMBOLSO POR MOTIVO DE CHUVA OU FRIO, INCLUSIVE SE O CLIENTE RECUSAR O REAGENDAMENTO PARA OS DIAS ÚTEIS. DA MESMA FORMA, SE A CHUVA COMEÇAR APÓS A MONTAGEM, NÃO SERÁ POSSÍVEL CANCELAR OU REAGENDAR, POIS O SERVIÇO JÁ TERÁ SIDO EFETIVAMENTE PRESTADO. POR FIM, EM CASO DE CANCELAMENTO OU DESISTÊNCIA POR INICIATIVA DO CLIENTE, O VALOR PAGO NÃO SERÁ DEVOLVIDO.',
  },
  {
    titulo: '8',
    texto:
      'TODO IMPEDIMENTO À REALIZAÇÃO DO SERVIÇO POR MOTIVO DE FALTA DE ENERGIA, FALTA DE ESPAÇO PARA O BRINQUEDO, ORGANIZAÇÃO OU OUTROS QUE NÃO SEJAM PROVOCADOS PELA PRESTADORA DE SERVIÇO SERÁ DE RESPONSABILIDADE DO CONTRATANTE. EM CASOS DE DIFICULDADE DE ACESSO, A EMPRESA DEVERÁ SER INFORMADA COM ANTECEDÊNCIA. CASO NÃO SEJA POSSÍVEL A MONTAGEM PELOS MOTIVOS CITADOS NESTE CONTRATO, A EMPRESA SE RESERVA O DIREITO DE CANCELAR A PRESTAÇÃO, REALIZANDO A COBRANÇA INTEGRAL DOS VALORES.',
  },
];
