import { TaskDraft } from './importLogistica';

const base = { precisaRevisao: false };

/** Logística de 03 e 04/10/2026 já revisada à mão a partir do PDF enviado (sem depender da leitura automática). */
export const LOGISTICA_3_E_4_OUTUBRO: TaskDraft[] = [
  { ...base, data: '2026-10-03', horario: '09:30', horarioComparacao: '09:30', tipo: 'MONTAGEM', cliente: 'ALACHERMA VIEIRA', brinquedo: 'FUTEBOL BRASIL', telefone: '19 99171-2885', endereco: 'CHÁCARA BRUNELLI - RUA FONTE MECIA, LOTE 20, BAIRRO SÃO PEDRO, VALINHOS/SP', valor: '450', observacoes: 'Gustavo (19 98966-1756) vai de moto até a casa e ajuda só nas montagens. Evento 11:30, retirada 17:00/18:15. CPF/CNPJ: 33915162833. Tempo estimado até aqui: 22 min.' },
  { ...base, data: '2026-10-03', horario: '10:30/11:00', horarioComparacao: '10:30', tipo: 'MONTAGEM', cliente: 'YULI ANDRÉA LINARES', brinquedo: 'FUTEBOL AZUL E LARANJA', telefone: '19 99223-7904', endereco: 'RUA ALAMEDA ITATINGA 1820 - JOAPIRANGA, VALINHOS - SP', valor: '500', observacoes: 'Evento 11:30, retirada 18:00/18:30.' },
  { ...base, data: '2026-10-03', horario: '12:00', horarioComparacao: '12:00', tipo: 'MONTAGEM', cliente: 'GABRIELA FRANCO', brinquedo: 'JACARÉ NOVO', telefone: '19 99937-8207', endereco: 'CONDOMÍNIO RESERVA COLONIAL - CHURRASQUEIRA 1 (condomínio onde o Matheus mora; ele orienta como chegar)', valor: '320', observacoes: 'Brinquedo separado em frente ao toldo com tudo que precisa. Pode estar sujo (foi em festa grande): dar uma geral e lembrar de passar produto para escorregar.' },
  { ...base, data: '2026-10-03', horario: '16:30', horarioComparacao: '16:30', tipo: 'LOGISTICA', cliente: 'Buscar ajudante Marcelo', telefone: '19 99187-1729', endereco: 'RUA JOSÉ CARLOS FERRARI - RES. SANTA MARIA, VALINHOS - SP (em frente ao trabalho dele, Espetaria Belo Boi)', observacoes: 'Marcelo faz as retiradas (tem mais experiência).' },
  { ...base, data: '2026-10-03', horario: '17:00', horarioComparacao: '17:00', tipo: 'RETIRADA', cliente: 'ALACHERMA VIEIRA', brinquedo: 'FUTEBOL BRASIL', telefone: '19 99171-2885', endereco: 'CHÁCARA BRUNELLI - RUA FONTE MECIA, LOTE 20, BAIRRO SÃO PEDRO, VALINHOS/SP', observacoes: 'Tempo estimado até aqui: 22 min.' },
  { ...base, data: '2026-10-03', horario: '18:00/18:30', horarioComparacao: '18:00', tipo: 'RETIRADA', cliente: 'YULI ANDRÉA LINARES', brinquedo: 'FUTEBOL AZUL E LARANJA', telefone: '19 99223-7904', endereco: 'RUA ALAMEDA ITATINGA 1820 - JOAPIRANGA, VALINHOS - SP' },
  { ...base, data: '2026-10-03', horario: '19:00', horarioComparacao: '19:00', tipo: 'RETIRADA', cliente: 'GABRIELA FRANCO', brinquedo: 'JACARÉ NOVO', telefone: '19 99937-8207', endereco: 'CONDOMÍNIO RESERVA COLONIAL - CHURRASQUEIRA 1', observacoes: 'Depois: descarregar tudo em casa e levar o Marcelo na casa dele.' },
  { ...base, data: '2026-10-04', horario: 'Até 12:30', horarioComparacao: '12:30', tipo: 'MONTAGEM', cliente: 'JULIANE BORSCHEID TRINDADE TRIVELATO', brinquedo: 'CAMA ELÁSTICA MÉDIA NOVA', telefone: '19 98214-4399', endereco: 'RUA JOÃO BISSOTO FILHO, N. 1690, SALÃO DR - Montagem no salão de festas do Condomínio Maison Blanche, VALINHOS/SP', valor: '180', observacoes: 'Brinquedo separado. Chegar antes das 12:30 (pode ser de manhã), combinar com a cliente.' },
];
