import { Task } from './types';

function checklist(items: string[]) {
  return items.map((texto, i) => ({ id: `c${i}`, texto, marcado: false }));
}

// Dados reais da operação, transcritos exatamente como informados.
// Servem apenas de carga inicial: uma vez que o usuário grava algo no
// IndexedDB, esses valores nunca são usados para sobrescrever.
export const INITIAL_TASKS: Omit<Task, 'status' | 'createdAt' | 'completedAt'>[] = [
  // ---------- 12/09/2026 ----------
  {
    id: 'seed-1',
    data: '2026-09-12',
    horario: '09:00',
    horarioComparacao: '09:00',
    tipo: 'LOGISTICA',
    cliente: 'Buscar Lelis',
    endereco: 'Rua Engenheiro Antônio Mayer, 218, Jardim Panorama, Valinhos - SP',
    cidade: 'Valinhos - SP',
    observacoes:
      'Tempo informado: 11 minutos. Previsão: 09:15. Retirada do ajudante posteriormente após 18:00.',
    checklist: [],
    ordem: 1,
  },
  {
    id: 'seed-2',
    data: '2026-09-12',
    horario: '09:15–09:30',
    horarioComparacao: '09:15',
    tipo: 'MONTAGEM',
    cliente: 'Jéssica dos Santos Pereira',
    telefone: '19 98460-3425',
    endereco: 'R. Vanessa Cristina Anselmi, 430, Chácaras São Bento, Valinhos - SP',
    cidade: 'Valinhos - SP',
    valor: 450,
    brinquedo: 'Futebol de Sabão',
    observacoes:
      'Identificação: Saco roxo. Dimensão: 10 x 5 metros. Cores: Cores do Brasil. Retirada: Após 18:00. Cobrar R$ 450,00 da cliente quando chegar.',
    checklist: checklist([
      'Deixar 8 detergentes na festa',
      'Bola de futebol',
      'Instalar mangueira caso não tenha no local',
      'Cobrir motor com o banco',
      'Colocar capa por cima',
      'Não tampar entrada de ar',
      'Amarrar capa para não soltar durante a festa',
    ]),
    ordem: 2,
  },
  {
    id: 'seed-3',
    data: '2026-09-12',
    horario: '10:30',
    horarioComparacao: '10:30',
    tipo: 'MONTAGEM',
    cliente: 'Cintia Alves de Sousa',
    telefone: '11 96822-9599',
    endereco: 'Condomínio Terras do Oriente, Rua João Previtale, 2760, Casa 256, Valinhos - SP',
    cidade: 'Valinhos - SP',
    valor: 320,
    brinquedo: 'Mini Tobogã com Piscina de Bolinhas',
    observacoes:
      'Identificação: Saco azul e amarelo. Retirada: Somente domingo. Cobrar R$ 320,00 quando chegar.',
    checklist: checklist([
      'Amarrar as laterais se possível',
      'Passar produto para escorregar',
      'Cobrir motor com o banco',
      'Cobrir com lona/capa',
      'Não fechar entrada de ar',
      'Amarrar capa',
    ]),
    ordem: 3,
  },
  {
    id: 'seed-4',
    data: '2026-09-12',
    horario: '16:00',
    horarioComparacao: '16:00',
    tipo: 'LOGISTICA',
    cliente: 'Buscar Lelis',
    endereco: 'Rua Engenheiro Antônio Mayer, 218, Jardim Panorama, Valinhos - SP',
    cidade: 'Valinhos - SP',
    observacoes: 'Objetivo: Buscar Lelis novamente para realizar retirada.',
    checklist: [],
    ordem: 4,
  },
  {
    id: 'seed-5',
    data: '2026-09-12',
    horario: '16:45–17:00',
    horarioComparacao: '16:45',
    tipo: 'RETIRADA',
    cliente: 'Rancho Oasis',
    brinquedo: 'Futebol Azul',
    endereco: 'Rodovia Adhemar de Barros (SP-340), Altura do KM 127,5, Bairro Tanquinho Velho, Jaguariúna - SP',
    cidade: 'Jaguariúna - SP',
    wazeQuery: 'Rancho Oasis',
    observacoes: 'No Waze procurar: Rancho Oasis. Priorizar Waze.',
    checklist: [],
    ordem: 5,
  },
  {
    id: 'seed-6',
    data: '2026-09-12',
    horario: 'Após 18:00',
    horarioComparacao: '18:00',
    tipo: 'RETIRADA',
    cliente: 'Jéssica dos Santos Pereira',
    telefone: '19 98460-3425',
    brinquedo: 'Futebol de Sabão — saco roxo',
    endereco: 'R. Vanessa Cristina Anselmi, 430, Chácaras São Bento, Valinhos - SP',
    cidade: 'Valinhos - SP',
    checklist: [],
    ordem: 6,
  },

  // ---------- 13/09/2026 ----------
  {
    id: 'seed-14',
    data: '2026-09-13',
    horario: '07:20',
    horarioComparacao: '07:20',
    tipo: 'LOGISTICA',
    cliente: 'Buscar Lelis',
    endereco: 'Rua Engenheiro Antônio Mayer, 218, Jardim Panorama, Valinhos - SP',
    cidade: 'Valinhos - SP',
    observacoes: 'Objetivo: Buscar Lelis para começar o dia.',
    checklist: [],
    ordem: 1,
  },
  {
    id: 'seed-7',
    data: '2026-09-13',
    horario: '08:00',
    horarioComparacao: '08:00',
    tipo: 'MONTAGEM',
    cliente: 'Viviane Cristina de Souza',
    telefone: '19 98143-4411',
    brinquedo: 'Futebol Azul',
    endereco: 'Rua José Ormeneze, 210, Vila João XXIII, Vinhedo - SP',
    cidade: 'Vinhedo - SP',
    valor: 500,
    observacoes: 'Retirada: Após 18:00. Cobrar R$ 500,00 quando chegar.',
    checklist: checklist([
      'Deixar 8 detergentes',
      'Bola de futebol',
      'Instalar mangueira caso não tenha',
      'Cobrir motor com banco',
      'Colocar capa por cima',
      'Não tampar entrada de ar',
      'Amarrar capa',
    ]),
    ordem: 2,
  },
  {
    id: 'seed-8',
    data: '2026-09-13',
    horario: '09:00–09:30',
    horarioComparacao: '09:00',
    tipo: 'MONTAGEM',
    cliente: 'Patrícia Rigonatti',
    telefone: '19 99445-3811',
    endereco: 'Rua Leonora Armstrong, 2655, Vila Pagano, Valinhos - SP',
    cidade: 'Valinhos - SP',
    valor: 400,
    observacoes:
      'Referência: Chácara Estância Santa Tereza, Antiga Estrada Estadual Campinas-São Paulo KM 93,5, Bairro Dois Córregos. Retirada: Após 17:00. Seguir localização do Google Maps. Fica em frente à empresa Lenze. Próximo ao Pague Menos.',
    checklist: checklist(['8 detergentes', 'Bola de futebol', 'Mangueira', 'Motor protegido', 'Entrada de ar livre', 'Capa amarrada']),
    ordem: 3,
  },
  {
    id: 'seed-15',
    data: '2026-09-13',
    horario: 'Após 2º cliente',
    horarioComparacao: '09:30',
    tipo: 'LOGISTICA',
    cliente: 'Ir para empresa',
    observacoes: 'Objetivo: Pegar a máquina de pipoca para levar ao evento SESI.',
    checklist: [],
    ordem: 4,
  },
  {
    id: 'seed-9',
    data: '2026-09-13',
    horario: 'Antes de 11:30',
    horarioComparacao: '11:30',
    tipo: 'EVENTO',
    cliente: 'SESI Campinas Amoreiras',
    telefone: '19 98871-2865',
    endereco: 'Av. das Amoreiras, 450, Parque Itália, Campinas - SP, CEP 13036-225',
    cidade: 'Campinas - SP',
    observacoes:
      'Chegar o mais cedo possível, antes de 11:30. Início das pipocas: no máximo 12:00. Contato: Rosana Gabriel. Não cobrar no local. Lelis ficará nesse evento — pedir para ele começar a preparar as pipocas e deixar bastante pipoca pronta. Comprar marmitex para vocês (se não houver tempo, comprar salgados) e deixar a marmitex com Lelis. Depois voltar para casa. Retornar aproximadamente 15:30. Às 16:00 iniciar retirada.',
    checklist: checklist([
      'Pipoqueira',
      'Barraca de pipoca',
      'Duas chapas de aço',
      'Telhado da barraca',
      'Pipoqueira elétrica',
      'Suportes para colocar as pipocas',
      'Materiais',
      'Caixas',
    ]),
    ordem: 5,
  },
  {
    id: 'seed-10',
    data: '2026-09-13',
    horario: '16:00',
    horarioComparacao: '16:00',
    tipo: 'RETIRADA',
    cliente: 'SESI Campinas Amoreiras',
    telefone: '19 98871-2865',
    endereco: 'Av. das Amoreiras, 450, Parque Itália, Campinas - SP, CEP 13036-225',
    cidade: 'Campinas - SP',
    observacoes: 'Contato: Rosana Gabriel.',
    checklist: checklist([
      'Retirar rapidamente',
      'Ter cuidado',
      'Não precisa limpar pipoqueira',
      'Descarregar em casa',
      'Levar pipoqueira para o quintal',
      'Colocar pipoqueira em cima da mesa',
      'Colocar no local dos demais brinquedos',
      'Evitar risco de quebrar',
    ]),
    ordem: 6,
  },
  {
    id: 'seed-11',
    data: '2026-09-13',
    horario: '17:00',
    horarioComparacao: '17:00',
    tipo: 'RETIRADA',
    cliente: 'Patrícia Rigonatti',
    telefone: '19 99445-3811',
    endereco: 'Rua Leonora Armstrong, 2655, Vila Pagano, Valinhos - SP',
    cidade: 'Valinhos - SP',
    observacoes:
      'Referência: Chácara Estância Santa Tereza, Bairro Dois Córregos, em frente à empresa Lenze, próximo ao Pague Menos. Prioridade de navegação: Waze.',
    checklist: [],
    ordem: 7,
  },
  {
    id: 'seed-12',
    data: '2026-09-13',
    horario: 'Após 18:00',
    horarioComparacao: '18:00',
    tipo: 'RETIRADA',
    cliente: 'Viviane Cristina de Souza',
    telefone: '19 98143-4411',
    brinquedo: 'Futebol Azul',
    endereco: 'Rua José Ormeneze, 210, Vila João XXIII, Vinhedo - SP',
    cidade: 'Vinhedo - SP',
    observacoes:
      'Tarefa adicional: passar no Ponto da Esfirra e pegar salgados — R. Treze de Maio, 427, Vila Olivo, Valinhos - SP.',
    checklist: checklist(['Se der tempo: ir para casa', 'Descarregar', 'Realizar última retirada']),
    ordem: 8,
  },
  {
    id: 'seed-13',
    data: '2026-09-13',
    horario: 'Após 20:00',
    horarioComparacao: '20:00',
    tipo: 'RETIRADA',
    cliente: 'Cintia Alves de Sousa',
    telefone: '11 96822-9599',
    brinquedo: 'Mini Tobogã com Piscina de Bolinhas',
    endereco: 'Condomínio Terras do Oriente, Rua João Previtale, 2760, Casa 256, Valinhos - SP',
    cidade: 'Valinhos - SP',
    checklist: checklist(['Retirar brinquedo', 'Deixar junto com os demais brinquedos']),
    ordem: 9,
  },
  {
    id: 'seed-16',
    data: '2026-09-13',
    horario: 'Após 20:00',
    horarioComparacao: '20:00',
    tipo: 'LOGISTICA',
    cliente: 'Descarregar tudo na empresa',
    observacoes: 'Descarregar tudo o que sobrou na empresa após a última retirada.',
    checklist: [],
    ordem: 10,
  },
  {
    id: 'seed-17',
    data: '2026-09-13',
    horario: 'Após 20:00',
    horarioComparacao: '20:00',
    tipo: 'LOGISTICA',
    cliente: 'Levar Lelis embora',
    checklist: [],
    ordem: 11,
  },
  {
    id: 'seed-18',
    data: '2026-09-13',
    horario: 'Após 20:00',
    horarioComparacao: '20:00',
    tipo: 'LOGISTICA',
    cliente: 'Voltar para empresa',
    checklist: [],
    ordem: 12,
  },
];
